[package]
name = "extension-lua"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-lua-base = { path = "../web-lua-base" }
web-lua-core = { path = "../web-lua-core" }
web-fs = { path = "../web-fs" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
data-encoding = "2.6"
tsify = "0.5"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "WorkerGlobalScope",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
