// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured error from running a cell.
 */
export type CellError = { "kind": "compile", message: string, line: number | null, } | { "kind": "runtime", message: string, } | { "kind": "strict_mode", variable: string, } | { "kind": "fuel_exhausted" } | { "kind": "internal", message: string, };

/**
 * A single global variable observed by `inspect_globals`.
 */
export type GlobalVariable = { name: string, type: string, value: string | null, keys: Array<string> | null, };

/**
 * Snapshot of all Lua globals.
 */
export type GlobalsSnapshot = { variables: Array<GlobalVariable>, execution_count: number, };
