use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::borrow::Cow;
use std::fmt;

/// Async action identifier.
/// Preserves flat string wire format while giving Rust compile-time variants.
#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Fetch,
    Sleep,
    MockAsync,
    DomSnapshot,
    DomFormat,
    StorageGet,
    StorageSet,
    StorageDelete,
    StorageList,
    PageClick,
    PageDblclick,
    PageFill,
    PageType,
    PagePress,
    PageSelect,
    PageCheck,
    PageHover,
    PageUnhover,
    PageScroll,
    PageScrollTo,
    PageUrl,
    PageTitle,
    PageSnapshot,
    PageSnapshotText,
    PageSnapshotData,
    PageScreenshot,
    PageGoto,
    PageBack,
    PageForward,
    PageReload,
    PageWait,
    PageTabs,
    PageSwitch,
    PageNewTab,
    PageClose,
    PageActiveTab,
    TabQuery,
    TabCreate,
    TabActivate,
    TabClose,
    TabExecuteScript,
    TabClick,
    TabFill,
    TabSnapshot,
    TabScrollTo,
    TabEvaluate,
    TabType,
    TabPress,
    TabSelect,
    TabCheck,
    TabHover,
    TabUnhover,
    TabScroll,
    TabDblclick,
    TabBack,
    TabWaitForLoad,
    TabFetch,
    CookiesGet,
    CookiesSet,
    CookiesDelete,
    CookiesList,
    HistorySearch,
    HistoryDelete,
    BookmarksSearch,
    BookmarksCreate,
    BookmarksDelete,
    NotificationsCreate,
    NotificationsClear,
    ClipboardRead,
    ClipboardWrite,
    ChromeRuntimeSendMessage,
    ChromeTabsQuery,
    ChromeTabsCreate,
    ChromeTabsUpdate,
    ChromeTabsRemove,
    ChromeTabsGet,
    ChromeTabsReload,
    ChromeTabsSendMessage,
    ChromeAlarmsCreate,
    ChromeAlarmsClear,
    ChromeActionSetBadgeText,
    ChromeActionSetBadgeBackgroundColor,
    ChromeActionSetTitle,
    ChromeActionSetIcon,
    ChromeContextMenusCreate,
    ChromeContextMenusRemove,
    ChromeWindowsGetAll,
    ChromeWindowsCreate,
    ChromeWindowsUpdate,
    ChromeWindowsRemove,
    ChromeSidePanelSetOptions,
    ChromeCookiesGet,
    ChromeCookiesSet,
    ChromeCookiesRemove,
    ChromeCookiesGetAll,
    ChromeBookmarksSearch,
    ChromeBookmarksCreate,
    ChromeBookmarksRemove,
    ChromeHistorySearch,
    ChromeHistoryDeleteUrl,
    ChromeNotificationsCreate,
    ChromeNotificationsClear,
    ChromeScriptingExecuteScript,
    RuntimeInspect,
    UrlParse,
    UrlEncode,
    WebLog,
    /// Dynamic extension escape hatch: host.call("myAction", {...})
    Host(String),
    /// Catch-all for unknown or extension-only actions.
    Other(String),
}

impl Action {
    pub fn as_str(&self) -> Cow<'_, str> {
        match self {
            Action::Fetch => Cow::Borrowed("fetch"),
            Action::Sleep => Cow::Borrowed("sleep"),
            Action::MockAsync => Cow::Borrowed("mock_async"),
            Action::DomSnapshot => Cow::Borrowed("dom_snapshot"),
            Action::DomFormat => Cow::Borrowed("dom_format"),
            Action::StorageGet => Cow::Borrowed("storage_get"),
            Action::StorageSet => Cow::Borrowed("storage_set"),
            Action::StorageDelete => Cow::Borrowed("storage_delete"),
            Action::StorageList => Cow::Borrowed("storage_list"),
            Action::PageClick => Cow::Borrowed("page_click"),
            Action::PageDblclick => Cow::Borrowed("page_dblclick"),
            Action::PageFill => Cow::Borrowed("page_fill"),
            Action::PageType => Cow::Borrowed("page_type"),
            Action::PagePress => Cow::Borrowed("page_press"),
            Action::PageSelect => Cow::Borrowed("page_select"),
            Action::PageCheck => Cow::Borrowed("page_check"),
            Action::PageHover => Cow::Borrowed("page_hover"),
            Action::PageUnhover => Cow::Borrowed("page_unhover"),
            Action::PageScroll => Cow::Borrowed("page_scroll"),
            Action::PageScrollTo => Cow::Borrowed("page_scroll_to"),
            Action::PageUrl => Cow::Borrowed("page_url"),
            Action::PageTitle => Cow::Borrowed("page_title"),
            Action::PageSnapshot => Cow::Borrowed("page_snapshot"),
            Action::PageSnapshotText => Cow::Borrowed("page_snapshot_text"),
            Action::PageSnapshotData => Cow::Borrowed("page_snapshot_data"),
            Action::PageScreenshot => Cow::Borrowed("page_screenshot"),
            Action::PageGoto => Cow::Borrowed("page_goto"),
            Action::PageBack => Cow::Borrowed("page_back"),
            Action::PageForward => Cow::Borrowed("page_forward"),
            Action::PageReload => Cow::Borrowed("page_reload"),
            Action::PageWait => Cow::Borrowed("page_wait"),
            Action::PageTabs => Cow::Borrowed("page_tabs"),
            Action::PageSwitch => Cow::Borrowed("page_switch"),
            Action::PageNewTab => Cow::Borrowed("page_new_tab"),
            Action::PageClose => Cow::Borrowed("page_close"),
            Action::PageActiveTab => Cow::Borrowed("page_active_tab"),
            Action::TabQuery => Cow::Borrowed("tab_query"),
            Action::TabCreate => Cow::Borrowed("tab_create"),
            Action::TabActivate => Cow::Borrowed("tab_activate"),
            Action::TabClose => Cow::Borrowed("tab_close"),
            Action::TabExecuteScript => Cow::Borrowed("tab_execute_script"),
            Action::TabClick => Cow::Borrowed("tab_click"),
            Action::TabFill => Cow::Borrowed("tab_fill"),
            Action::TabSnapshot => Cow::Borrowed("tab_snapshot"),
            Action::TabScrollTo => Cow::Borrowed("tab_scroll_to"),
            Action::TabEvaluate => Cow::Borrowed("tab_evaluate"),
            Action::TabType => Cow::Borrowed("tab_type"),
            Action::TabPress => Cow::Borrowed("tab_press"),
            Action::TabSelect => Cow::Borrowed("tab_select"),
            Action::TabCheck => Cow::Borrowed("tab_check"),
            Action::TabHover => Cow::Borrowed("tab_hover"),
            Action::TabUnhover => Cow::Borrowed("tab_unhover"),
            Action::TabScroll => Cow::Borrowed("tab_scroll"),
            Action::TabDblclick => Cow::Borrowed("tab_dblclick"),
            Action::TabBack => Cow::Borrowed("tab_back"),
            Action::TabWaitForLoad => Cow::Borrowed("tab_wait_for_load"),
            Action::TabFetch => Cow::Borrowed("tab_fetch"),
            Action::CookiesGet => Cow::Borrowed("cookies_get"),
            Action::CookiesSet => Cow::Borrowed("cookies_set"),
            Action::CookiesDelete => Cow::Borrowed("cookies_delete"),
            Action::CookiesList => Cow::Borrowed("cookies_list"),
            Action::HistorySearch => Cow::Borrowed("history_search"),
            Action::HistoryDelete => Cow::Borrowed("history_delete"),
            Action::BookmarksSearch => Cow::Borrowed("bookmarks_search"),
            Action::BookmarksCreate => Cow::Borrowed("bookmarks_create"),
            Action::BookmarksDelete => Cow::Borrowed("bookmarks_delete"),
            Action::NotificationsCreate => Cow::Borrowed("notifications_create"),
            Action::NotificationsClear => Cow::Borrowed("notifications_clear"),
            Action::ClipboardRead => Cow::Borrowed("clipboard_read"),
            Action::ClipboardWrite => Cow::Borrowed("clipboard_write"),
            Action::ChromeRuntimeSendMessage => Cow::Borrowed("chrome_runtime_sendMessage"),
            Action::ChromeTabsQuery => Cow::Borrowed("chrome_tabs_query"),
            Action::ChromeTabsCreate => Cow::Borrowed("chrome_tabs_create"),
            Action::ChromeTabsUpdate => Cow::Borrowed("chrome_tabs_update"),
            Action::ChromeTabsRemove => Cow::Borrowed("chrome_tabs_remove"),
            Action::ChromeTabsGet => Cow::Borrowed("chrome_tabs_get"),
            Action::ChromeTabsReload => Cow::Borrowed("chrome_tabs_reload"),
            Action::ChromeTabsSendMessage => Cow::Borrowed("chrome_tabs_sendMessage"),
            Action::ChromeAlarmsCreate => Cow::Borrowed("chrome_alarms_create"),
            Action::ChromeAlarmsClear => Cow::Borrowed("chrome_alarms_clear"),
            Action::ChromeActionSetBadgeText => Cow::Borrowed("chrome_action_setBadgeText"),
            Action::ChromeActionSetBadgeBackgroundColor => {
                Cow::Borrowed("chrome_action_setBadgeBackgroundColor")
            }
            Action::ChromeActionSetTitle => Cow::Borrowed("chrome_action_setTitle"),
            Action::ChromeActionSetIcon => Cow::Borrowed("chrome_action_setIcon"),
            Action::ChromeContextMenusCreate => Cow::Borrowed("chrome_contextMenus_create"),
            Action::ChromeContextMenusRemove => Cow::Borrowed("chrome_contextMenus_remove"),
            Action::ChromeWindowsGetAll => Cow::Borrowed("chrome_windows_getAll"),
            Action::ChromeWindowsCreate => Cow::Borrowed("chrome_windows_create"),
            Action::ChromeWindowsUpdate => Cow::Borrowed("chrome_windows_update"),
            Action::ChromeWindowsRemove => Cow::Borrowed("chrome_windows_remove"),
            Action::ChromeSidePanelSetOptions => Cow::Borrowed("chrome_sidePanel_setOptions"),
            Action::ChromeCookiesGet => Cow::Borrowed("chrome_cookies_get"),
            Action::ChromeCookiesSet => Cow::Borrowed("chrome_cookies_set"),
            Action::ChromeCookiesRemove => Cow::Borrowed("chrome_cookies_remove"),
            Action::ChromeCookiesGetAll => Cow::Borrowed("chrome_cookies_getAll"),
            Action::ChromeBookmarksSearch => Cow::Borrowed("chrome_bookmarks_search"),
            Action::ChromeBookmarksCreate => Cow::Borrowed("chrome_bookmarks_create"),
            Action::ChromeBookmarksRemove => Cow::Borrowed("chrome_bookmarks_remove"),
            Action::ChromeHistorySearch => Cow::Borrowed("chrome_history_search"),
            Action::ChromeHistoryDeleteUrl => Cow::Borrowed("chrome_history_deleteUrl"),
            Action::ChromeNotificationsCreate => Cow::Borrowed("chrome_notifications_create"),
            Action::ChromeNotificationsClear => Cow::Borrowed("chrome_notifications_clear"),
            Action::ChromeScriptingExecuteScript => Cow::Borrowed("chrome_scripting_executeScript"),
            Action::RuntimeInspect => Cow::Borrowed("runtime_inspect"),
            Action::UrlParse => Cow::Borrowed("url_parse"),
            Action::UrlEncode => Cow::Borrowed("url_encode"),
            Action::WebLog => Cow::Borrowed("web_log"),
            Action::Host(s) => Cow::Owned(format!("host_{}", s)),
            Action::Other(s) => Cow::Borrowed(s.as_str()),
        }
    }

    pub fn is_host(&self) -> bool {
        matches!(self, Action::Host(_))
    }

    pub fn host_action(&self) -> Option<&str> {
        match self {
            Action::Host(s) => Some(s.as_str()),
            _ => None,
        }
    }
}

impl fmt::Display for Action {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str().as_ref())
    }
}

impl Serialize for Action {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str().as_ref())
    }
}

impl<'de> Deserialize<'de> for Action {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        Ok(match s.as_str() {
            "fetch" => Action::Fetch,
            "sleep" => Action::Sleep,
            "mock_async" => Action::MockAsync,
            "dom_snapshot" => Action::DomSnapshot,
            "dom_format" => Action::DomFormat,
            "storage_get" => Action::StorageGet,
            "storage_set" => Action::StorageSet,
            "storage_delete" => Action::StorageDelete,
            "storage_list" => Action::StorageList,
            "page_click" => Action::PageClick,
            "page_dblclick" => Action::PageDblclick,
            "page_fill" => Action::PageFill,
            "page_type" => Action::PageType,
            "page_press" => Action::PagePress,
            "page_select" => Action::PageSelect,
            "page_check" => Action::PageCheck,
            "page_hover" => Action::PageHover,
            "page_unhover" => Action::PageUnhover,
            "page_scroll" => Action::PageScroll,
            "page_scroll_to" => Action::PageScrollTo,
            "page_url" => Action::PageUrl,
            "page_title" => Action::PageTitle,
            "page_screenshot" => Action::PageScreenshot,
            "page_snapshot" => Action::PageSnapshot,
            "page_snapshot_text" => Action::PageSnapshotText,
            "page_snapshot_data" => Action::PageSnapshotData,
            "page_goto" => Action::PageGoto,
            "page_back" => Action::PageBack,
            "page_forward" => Action::PageForward,
            "page_reload" => Action::PageReload,
            "page_wait" => Action::PageWait,
            "page_tabs" => Action::PageTabs,
            "page_switch" => Action::PageSwitch,
            "page_new_tab" => Action::PageNewTab,
            "page_close" => Action::PageClose,
            "page_active_tab" => Action::PageActiveTab,
            "tab_query" => Action::TabQuery,
            "tab_create" => Action::TabCreate,
            "tab_activate" => Action::TabActivate,
            "tab_close" => Action::TabClose,
            "tab_execute_script" => Action::TabExecuteScript,
            "tab_click" => Action::TabClick,
            "tab_fill" => Action::TabFill,
            "tab_snapshot" => Action::TabSnapshot,
            "tab_scroll_to" => Action::TabScrollTo,
            "tab_evaluate" => Action::TabEvaluate,
            "tab_type" => Action::TabType,
            "tab_press" => Action::TabPress,
            "tab_select" => Action::TabSelect,
            "tab_check" => Action::TabCheck,
            "tab_hover" => Action::TabHover,
            "tab_unhover" => Action::TabUnhover,
            "tab_scroll" => Action::TabScroll,
            "tab_dblclick" => Action::TabDblclick,
            "tab_back" => Action::TabBack,
            "tab_wait_for_load" => Action::TabWaitForLoad,
            "tab_fetch" => Action::TabFetch,
            "cookies_get" => Action::CookiesGet,
            "cookies_set" => Action::CookiesSet,
            "cookies_delete" => Action::CookiesDelete,
            "cookies_list" => Action::CookiesList,
            "history_search" => Action::HistorySearch,
            "history_delete" => Action::HistoryDelete,
            "bookmarks_search" => Action::BookmarksSearch,
            "bookmarks_create" => Action::BookmarksCreate,
            "bookmarks_delete" => Action::BookmarksDelete,
            "notifications_create" => Action::NotificationsCreate,
            "notifications_clear" => Action::NotificationsClear,
            "clipboard_read" => Action::ClipboardRead,
            "clipboard_write" => Action::ClipboardWrite,
            "chrome_runtime_sendMessage" => Action::ChromeRuntimeSendMessage,
            "chrome_tabs_query" => Action::ChromeTabsQuery,
            "chrome_tabs_create" => Action::ChromeTabsCreate,
            "chrome_tabs_update" => Action::ChromeTabsUpdate,
            "chrome_tabs_remove" => Action::ChromeTabsRemove,
            "chrome_tabs_get" => Action::ChromeTabsGet,
            "chrome_tabs_reload" => Action::ChromeTabsReload,
            "chrome_tabs_sendMessage" => Action::ChromeTabsSendMessage,
            "chrome_alarms_create" => Action::ChromeAlarmsCreate,
            "chrome_alarms_clear" => Action::ChromeAlarmsClear,
            "chrome_action_setBadgeText" => Action::ChromeActionSetBadgeText,
            "chrome_action_setBadgeBackgroundColor" => Action::ChromeActionSetBadgeBackgroundColor,
            "chrome_action_setTitle" => Action::ChromeActionSetTitle,
            "chrome_action_setIcon" => Action::ChromeActionSetIcon,
            "chrome_contextMenus_create" => Action::ChromeContextMenusCreate,
            "chrome_contextMenus_remove" => Action::ChromeContextMenusRemove,
            "chrome_windows_getAll" => Action::ChromeWindowsGetAll,
            "chrome_windows_create" => Action::ChromeWindowsCreate,
            "chrome_windows_update" => Action::ChromeWindowsUpdate,
            "chrome_windows_remove" => Action::ChromeWindowsRemove,
            "chrome_sidePanel_setOptions" => Action::ChromeSidePanelSetOptions,
            "chrome_cookies_get" => Action::ChromeCookiesGet,
            "chrome_cookies_set" => Action::ChromeCookiesSet,
            "chrome_cookies_remove" => Action::ChromeCookiesRemove,
            "chrome_cookies_getAll" => Action::ChromeCookiesGetAll,
            "chrome_bookmarks_search" => Action::ChromeBookmarksSearch,
            "chrome_bookmarks_create" => Action::ChromeBookmarksCreate,
            "chrome_bookmarks_remove" => Action::ChromeBookmarksRemove,
            "chrome_history_search" => Action::ChromeHistorySearch,
            "chrome_history_deleteUrl" => Action::ChromeHistoryDeleteUrl,
            "chrome_notifications_create" => Action::ChromeNotificationsCreate,
            "chrome_notifications_clear" => Action::ChromeNotificationsClear,
            "chrome_scripting_executeScript" => Action::ChromeScriptingExecuteScript,
            "runtime_inspect" => Action::RuntimeInspect,
            "url_parse" => Action::UrlParse,
            "url_encode" => Action::UrlEncode,
            "web_log" => Action::WebLog,
            s if s.starts_with("host_") => Action::Host(s[5..].to_string()),
            _ => Action::Other(s),
        })
    }
}

impl From<&str> for Action {
    fn from(s: &str) -> Self {
        match s {
            "fetch" => Action::Fetch,
            "sleep" => Action::Sleep,
            "mock_async" => Action::MockAsync,
            "dom_snapshot" => Action::DomSnapshot,
            "dom_format" => Action::DomFormat,
            "storage_get" => Action::StorageGet,
            "storage_set" => Action::StorageSet,
            "storage_delete" => Action::StorageDelete,
            "storage_list" => Action::StorageList,
            "page_click" => Action::PageClick,
            "page_dblclick" => Action::PageDblclick,
            "page_fill" => Action::PageFill,
            "page_type" => Action::PageType,
            "page_press" => Action::PagePress,
            "page_select" => Action::PageSelect,
            "page_check" => Action::PageCheck,
            "page_hover" => Action::PageHover,
            "page_unhover" => Action::PageUnhover,
            "page_scroll" => Action::PageScroll,
            "page_scroll_to" => Action::PageScrollTo,
            "page_url" => Action::PageUrl,
            "page_title" => Action::PageTitle,
            "page_screenshot" => Action::PageScreenshot,
            "page_snapshot" => Action::PageSnapshot,
            "page_snapshot_text" => Action::PageSnapshotText,
            "page_snapshot_data" => Action::PageSnapshotData,
            "page_goto" => Action::PageGoto,
            "page_back" => Action::PageBack,
            "page_forward" => Action::PageForward,
            "page_reload" => Action::PageReload,
            "page_wait" => Action::PageWait,
            "page_tabs" => Action::PageTabs,
            "page_switch" => Action::PageSwitch,
            "page_new_tab" => Action::PageNewTab,
            "page_close" => Action::PageClose,
            "page_active_tab" => Action::PageActiveTab,
            "tab_query" => Action::TabQuery,
            "tab_create" => Action::TabCreate,
            "tab_activate" => Action::TabActivate,
            "tab_close" => Action::TabClose,
            "tab_execute_script" => Action::TabExecuteScript,
            "tab_click" => Action::TabClick,
            "tab_fill" => Action::TabFill,
            "tab_snapshot" => Action::TabSnapshot,
            "tab_scroll_to" => Action::TabScrollTo,
            "tab_evaluate" => Action::TabEvaluate,
            "tab_type" => Action::TabType,
            "tab_press" => Action::TabPress,
            "tab_select" => Action::TabSelect,
            "tab_check" => Action::TabCheck,
            "tab_hover" => Action::TabHover,
            "tab_unhover" => Action::TabUnhover,
            "tab_scroll" => Action::TabScroll,
            "tab_dblclick" => Action::TabDblclick,
            "tab_back" => Action::TabBack,
            "tab_wait_for_load" => Action::TabWaitForLoad,
            "tab_fetch" => Action::TabFetch,
            "cookies_get" => Action::CookiesGet,
            "cookies_set" => Action::CookiesSet,
            "cookies_delete" => Action::CookiesDelete,
            "cookies_list" => Action::CookiesList,
            "history_search" => Action::HistorySearch,
            "history_delete" => Action::HistoryDelete,
            "bookmarks_search" => Action::BookmarksSearch,
            "bookmarks_create" => Action::BookmarksCreate,
            "bookmarks_delete" => Action::BookmarksDelete,
            "notifications_create" => Action::NotificationsCreate,
            "notifications_clear" => Action::NotificationsClear,
            "clipboard_read" => Action::ClipboardRead,
            "clipboard_write" => Action::ClipboardWrite,
            "chrome_runtime_sendMessage" => Action::ChromeRuntimeSendMessage,
            "chrome_tabs_query" => Action::ChromeTabsQuery,
            "chrome_tabs_create" => Action::ChromeTabsCreate,
            "chrome_tabs_update" => Action::ChromeTabsUpdate,
            "chrome_tabs_remove" => Action::ChromeTabsRemove,
            "chrome_tabs_get" => Action::ChromeTabsGet,
            "chrome_tabs_reload" => Action::ChromeTabsReload,
            "chrome_tabs_sendMessage" => Action::ChromeTabsSendMessage,
            "chrome_alarms_create" => Action::ChromeAlarmsCreate,
            "chrome_alarms_clear" => Action::ChromeAlarmsClear,
            "chrome_action_setBadgeText" => Action::ChromeActionSetBadgeText,
            "chrome_action_setBadgeBackgroundColor" => Action::ChromeActionSetBadgeBackgroundColor,
            "chrome_action_setTitle" => Action::ChromeActionSetTitle,
            "chrome_action_setIcon" => Action::ChromeActionSetIcon,
            "chrome_contextMenus_create" => Action::ChromeContextMenusCreate,
            "chrome_contextMenus_remove" => Action::ChromeContextMenusRemove,
            "chrome_windows_getAll" => Action::ChromeWindowsGetAll,
            "chrome_windows_create" => Action::ChromeWindowsCreate,
            "chrome_windows_update" => Action::ChromeWindowsUpdate,
            "chrome_windows_remove" => Action::ChromeWindowsRemove,
            "chrome_sidePanel_setOptions" => Action::ChromeSidePanelSetOptions,
            "chrome_cookies_get" => Action::ChromeCookiesGet,
            "chrome_cookies_set" => Action::ChromeCookiesSet,
            "chrome_cookies_remove" => Action::ChromeCookiesRemove,
            "chrome_cookies_getAll" => Action::ChromeCookiesGetAll,
            "chrome_bookmarks_search" => Action::ChromeBookmarksSearch,
            "chrome_bookmarks_create" => Action::ChromeBookmarksCreate,
            "chrome_bookmarks_remove" => Action::ChromeBookmarksRemove,
            "chrome_history_search" => Action::ChromeHistorySearch,
            "chrome_history_deleteUrl" => Action::ChromeHistoryDeleteUrl,
            "chrome_notifications_create" => Action::ChromeNotificationsCreate,
            "chrome_notifications_clear" => Action::ChromeNotificationsClear,
            "chrome_scripting_executeScript" => Action::ChromeScriptingExecuteScript,
            "runtime_inspect" => Action::RuntimeInspect,
            "url_parse" => Action::UrlParse,
            "url_encode" => Action::UrlEncode,
            "web_log" => Action::WebLog,
            s if s.starts_with("host_") => Action::Host(s[5..].to_string()),
            _ => Action::Other(s.to_string()),
        }
    }
}

impl From<String> for Action {
    fn from(s: String) -> Self {
        Self::from(s.as_str())
    }
}

impl From<Action> for String {
    fn from(a: Action) -> Self {
        a.as_str().into_owned()
    }
}
