[target.wasm32-unknown-emscripten]
linker = "emcc"
rustflags = [
    "-C", "panic=abort",
    "-C", "link-args=-sMODULARIZE=1",
    "-C", "link-args=-sEXPORT_NAME=createLuaModule",
    "-C", "link-args=-sEXPORTED_FUNCTIONS=['_run_lua','_free']",
    "-C", "link-args=-sEXPORTED_RUNTIME_METHODS=['ccall','UTF8ToString','stringToUTF8','lengthBytesUTF8']",
    "-C", "link-args=-sALLOW_MEMORY_GROWTH=1",
    "-C", "link-args=-sENVIRONMENT=web,worker",
    "-C", "link-args=-sSUPPORT_LONGJMP=wasm",
    "-C", "link-args=-sERROR_ON_UNDEFINED_SYMBOLS=0",
    "-C", "link-args=-O2",
]
